services:
  - type: web
    name: huntr-backend
    env: python
    pythonVersion: "3.13.4"
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    envVars:
      - key: DEBUG
        value: "False"
      - key: API_URL
        fromService:
          name: huntr-backend
          property: url

  - type: redis
    name: job-hunter-cache
    plan: free
    region: oregon